import 'server-only';
import crypto from 'crypto';
import bcrypt from 'bcryptjs';
import { cookies } from 'next/headers';

// Client.role is a plain string column (SQLite has no enums), so the union
// lives here rather than being generated by Prisma.
export type Role = 'ADMIN' | 'SALES' | 'B2B' | 'RETAIL';

/** Narrows the raw `role` string off a Client row. Anything unrecognised
 *  falls back to the least-privileged role. */
export function toRole(value: string | null | undefined): Role {
  return value === 'ADMIN' || value === 'SALES' || value === 'B2B' ? value : 'RETAIL';
}

/**
 * The value `.env.example` ships with, and what development falls back to.
 *
 * It is published — it is in the example file, the README and the git history
 * — so it is a secret in name only. Anyone who has seen this repository can
 * mint an ADMIN cookie for any deployment still signing with it.
 */
const DEV_PLACEHOLDER = 'dev-only-insecure-secret-change-me';

/**
 * `openssl rand -hex 32`, the command the README gives, produces 64
 * characters. The floor is set well under that so a different but sound
 * generator is not refused, and well over anything worth guessing at.
 */
const MIN_SECRET_LENGTH = 32;

/**
 * The signing key, or a refusal to start signing with a known one.
 *
 * Development keeps the placeholder, because a local app that will not run
 * until you invent a secret is a worse first five minutes for no gain. In
 * production the three ways to end up forgeable — unset, still the example
 * value, or something too short to matter — all stop here instead.
 *
 * Pure, and exported, so the rules can be tested without a process to set
 * environment variables on.
 */
export function resolveAuthSecret(
  configured: string | undefined,
  nodeEnv: string | undefined
): string {
  if (nodeEnv !== 'production') return configured || DEV_PLACEHOLDER;

  if (!configured) {
    throw new Error(
      'AUTH_SECRET is not set. Sessions would be signed with a published ' +
        'placeholder, so anyone could forge an admin cookie. Generate one ' +
        'with `openssl rand -hex 32`.'
    );
  }
  if (configured === DEV_PLACEHOLDER) {
    throw new Error(
      'AUTH_SECRET is still the value from .env.example, which is published ' +
        'and lets anyone forge an admin cookie. Generate one with ' +
        '`openssl rand -hex 32`.'
    );
  }
  if (configured.length < MIN_SECRET_LENGTH) {
    throw new Error(
      `AUTH_SECRET is ${configured.length} characters; ${MIN_SECRET_LENGTH} is ` +
        'the minimum. Generate one with `openssl rand -hex 32`.'
    );
  }

  return configured;
}

/**
 * Resolved on first use rather than at import.
 *
 * `next build` runs with NODE_ENV=production, so checking at module load
 * would make a build fail wherever the secret is not also a build-time
 * variable — the same coupling the README deliberately avoids for the
 * database. Checking here means the failure lands on the first request that
 * touches a session instead, which is a signing attempt, which is exactly
 * where it belongs.
 */
let resolvedSecret: string | null = null;

function secret(): string {
  return (resolvedSecret ??= resolveAuthSecret(process.env.AUTH_SECRET, process.env.NODE_ENV));
}

export const SESSION_COOKIE = 'aph_session';
const MAX_AGE_SECONDS = 60 * 60 * 24 * 7; // 7 days

export interface SessionPayload {
  userId: string;
  role: Role;
  categoryId: string | null;
  name: string;
  exp: number;
}

// ---- passwords ----

export async function hashPassword(password: string): Promise<string> {
  return bcrypt.hash(password, 10);
}

export async function verifyPassword(password: string, hash: string): Promise<boolean> {
  return bcrypt.compare(password, hash);
}

// ---- signed session token (HMAC — no external JWT dep needed) ----

function sign(data: string): string {
  return crypto.createHmac('sha256', secret()).update(data).digest('base64url');
}

function encodeSession(payload: SessionPayload): string {
  const body = Buffer.from(JSON.stringify(payload)).toString('base64url');
  return `${body}.${sign(body)}`;
}

export function decodeSession(token: string | undefined | null): SessionPayload | null {
  if (!token) return null;
  const [body, sig] = token.split('.');
  if (!body || !sig) return null;
  if (sign(body) !== sig) return null; // tampered or forged
  try {
    const payload = JSON.parse(Buffer.from(body, 'base64url').toString('utf8')) as SessionPayload;
    if (payload.exp < Date.now()) return null; // expired
    return payload;
  } catch {
    return null;
  }
}

// ---- cookie helpers (Server Actions / Route Handlers only) ----

export async function createSession(user: { id: string; role: string; categoryId: string | null; name: string }) {
  const payload: SessionPayload = {
    userId: user.id,
    role: toRole(user.role),
    categoryId: user.categoryId,
    name: user.name,
    exp: Date.now() + MAX_AGE_SECONDS * 1000,
  };
  cookies().set(SESSION_COOKIE, encodeSession(payload), {
    httpOnly: true,
    sameSite: 'lax',
    secure: process.env.NODE_ENV === 'production',
    maxAge: MAX_AGE_SECONDS,
    path: '/',
  });
}

export async function destroySession() {
  cookies().set(SESSION_COOKIE, '', { maxAge: 0, path: '/' });
}

export async function getSession(): Promise<SessionPayload | null> {
  const token = cookies().get(SESSION_COOKIE)?.value;
  return decodeSession(token);
}
