import 'server-only';
import crypto from 'crypto';
import bcrypt from 'bcryptjs';
import { cookies } from 'next/headers';

// Client.role is a plain string column (SQLite has no enums), so the union
// lives here rather than being generated by Prisma.
export type Role = 'ADMIN' | 'B2B' | 'RETAIL';

/** Narrows the raw `role` string off a Client row. Anything unrecognised
 *  falls back to the least-privileged role. */
export function toRole(value: string | null | undefined): Role {
  return value === 'ADMIN' || value === 'B2B' ? value : 'RETAIL';
}

const SECRET = process.env.AUTH_SECRET || 'dev-only-insecure-secret-change-me';
export const SESSION_COOKIE = 'aph_session';
const MAX_AGE_SECONDS = 60 * 60 * 24 * 7; // 7 days

export interface SessionPayload {
  userId: string;
  role: Role;
  categoryId: string | null;
  name: string;
  exp: number;
}

// ---- passwords ----

export async function hashPassword(password: string): Promise<string> {
  return bcrypt.hash(password, 10);
}

export async function verifyPassword(password: string, hash: string): Promise<boolean> {
  return bcrypt.compare(password, hash);
}

// ---- signed session token (HMAC — no external JWT dep needed) ----

function sign(data: string): string {
  return crypto.createHmac('sha256', SECRET).update(data).digest('base64url');
}

function encodeSession(payload: SessionPayload): string {
  const body = Buffer.from(JSON.stringify(payload)).toString('base64url');
  return `${body}.${sign(body)}`;
}

export function decodeSession(token: string | undefined | null): SessionPayload | null {
  if (!token) return null;
  const [body, sig] = token.split('.');
  if (!body || !sig) return null;
  if (sign(body) !== sig) return null; // tampered or forged
  try {
    const payload = JSON.parse(Buffer.from(body, 'base64url').toString('utf8')) as SessionPayload;
    if (payload.exp < Date.now()) return null; // expired
    return payload;
  } catch {
    return null;
  }
}

// ---- cookie helpers (Server Actions / Route Handlers only) ----

export async function createSession(user: { id: string; role: string; categoryId: string | null; name: string }) {
  const payload: SessionPayload = {
    userId: user.id,
    role: toRole(user.role),
    categoryId: user.categoryId,
    name: user.name,
    exp: Date.now() + MAX_AGE_SECONDS * 1000,
  };
  cookies().set(SESSION_COOKIE, encodeSession(payload), {
    httpOnly: true,
    sameSite: 'lax',
    secure: process.env.NODE_ENV === 'production',
    maxAge: MAX_AGE_SECONDS,
    path: '/',
  });
}

export async function destroySession() {
  cookies().set(SESSION_COOKIE, '', { maxAge: 0, path: '/' });
}

export async function getSession(): Promise<SessionPayload | null> {
  const token = cookies().get(SESSION_COOKIE)?.value;
  return decodeSession(token);
}
